import { describe, it, expect, vi, beforeEach } from "vitest";

// The shared fe-core double returns the value unchanged for `formatGQLString`;
// mark it here to assert that every text value actually goes through it.
const { escape } = vi.hoisted(() => ({ escape: vi.fn((value) => `esc(${value})`) }));

vi.mock("@openimis/fe-core", async (importOriginal) => {
  const actual = await importOriginal();
  return { ...actual, formatGQLString: escape };
});

import { formatMutation } from "@openimis/fe-core";
import { createPaymentInvoiceWithDetail } from "../src/actions";

const DESTINATION = "01a0ab26-c294-7a98-b868-f64b425a7f90";
const PARTY = "01a04401-f342-7fa9-9fef-6455efa7d027";

const payment = (overrides = {}) => ({
  status: 1,
  reconciliationStatus: 0,
  fees: "0.00",
  amountReceived: "10000.00",
  datePayment: "2026-09-24",
  paymentOrigin: "CHEQUE",
  codeExt: "PAY-1",
  payerRef: "REF-0042",
  paymentDestinationId: DESTINATION,
  partyId: PARTY,
  ...overrides,
});

/** Input generated by the builder (the action only exposes the thunk). */
const buildInput = (overrides = {}) => {
  formatMutation.mockClear();
  escape.mockClear();
  createPaymentInvoiceWithDetail(payment(overrides), "invoice-uuid", "invoice", "Create Payment");
  return String(formatMutation.mock.calls[0][1]);
};

describe("createPaymentInvoiceWithDetail payload", () => {
  beforeEach(() => formatMutation.mockClear());

  it("sends the ledger UUIDs of the payment destination and the third party", () => {
    const input = buildInput();

    expect(input).toContain(`paymentDestinationId: "esc(${DESTINATION})"`);
    expect(input).toContain(`partyId: "esc(${PARTY})"`);
    expect(input).toContain('subjectId: "esc(invoice-uuid)"');
    expect(input).toContain('subjectType: "esc(invoice)"');
    expect(input).toContain('payerRef: "esc(REF-0042)"');
    expect(input).toContain("status: 1");
    // 0 is a meaningful value for these two: 0 = not reconciliated, no fees.
    expect(input).toContain("reconciliationStatus: 0");
    expect(input).toContain('fees: "esc(0.00)"');
  });

  it("escapes every text value, so a quote can no longer break the document", () => {
    buildInput({ payerRef: 'REF"0042', codeExt: "PAY\\1" });

    expect(escape).toHaveBeenCalledWith('REF"0042');
    expect(escape).toHaveBeenCalledWith("PAY\\1");
    expect(escape).toHaveBeenCalledWith("10000.00");
  });

  it("omits the optional ledger fields when they are empty", () => {
    const input = buildInput({ paymentDestinationId: null, partyId: undefined });

    expect(input).not.toContain("paymentDestinationId");
    expect(input).not.toContain("partyId");
    expect(input).not.toMatch(/:\s*null\b/);
  });
});
